module.exports = {
    a0:"/pdf/coomapn-opening-letter",
    a1: '/pdfs/activation-link',
    a2: '/mail/activation-link',
    a3: "/mail/first-call-val",
    a4: '/mail/coomapn-welcome',
    a5: '/pdf/fxInvoice',
    a6: '/mail/bene-confirm',
    a7: '/mail/bene-confirm-first',
    a8: '/mail/bene-confirm-second',
    a9: '/mail/welcome-email',
    a10: '/mail/welcome',
    a11: '/month',
    a12: '/month-template',
    statements: '/statement-template',
    confirm: '/payment/confirmation',
    audit: '/payment/audit',
    details: '/payment/details',
    userAct: '/',
    invoice: '/invoicePdf',
    returnPay: '/pdfs/return-payment',
    returnInv: '/invoiceReturnPdf',
    resetSecQ: '/pdfs/reset-security-answers',
    minAge: '/pdfs/reset-password-min-age',
    passwordLink: '/pdfs/reset-password-link',
    passwordAdmin: '/pdfs/reset-password-admin',
    notif: '/pdfs/notification',
    notifIn: '/pdfs/notification-i',
    notifInF: '/pdfs/notification-i-f',
    know: '/pdfs/know-your-customer',
    custom: '/pdfs/custom',
    welcome: '/pdfs/client-welcome',
    invData: '/pdfs/invoice-data'
};
